BEGIN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE course_access ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE course_access ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
ALTER TABLE course_access ADD COLUMN IF NOT EXISTS approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE course_access ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMPTZ;
COMMIT;
